VerisimilarGM.zoneList={};
VerisimilarGM.zoneList.easternKingdoms={"Alterac Mountains","Arathi Highlands","Badlands","Blackrock Mountain","Blasted Lands","Burning Steppes","Deadwind Pass","Deeprun Tram","Dun Morogh","Duskwood","Eastern Plaguelands","Elwynn Forest","Eversong Woods","Ghostlands","Hillsbrad Foothills","Ironforge","Isle of Quel'Danas","Loch Modan","Redridge Mountains","Searing Gorge","Silvermoon City","Silverpine Forest","Stormwind City","Stranglethorn Vale","Swamp of Sorrows","The Hinterlands","Plaguelands: The Scarlet Enclave","Tirisfal Glades","Undercity","Western Plaguelands","Westfall","Wetlands"};
VerisimilarGM.zoneList.kalimdor={"Ashenvale","Azshara",
"Azuremyst Isle",
"Bloodmyst Isle",
"Darkshore",
"Darnassus",
"Desolace",
"Durotar",
"Dustwallow Marsh",
"Felwood",
"Feralas",
"Moonglade",
"Mulgore",
"Orgrimmar",
"Silithus",
"Stonetalon Mountains",
"Tanaris",
"Teldrassil",
"The Barrens",
"The Exodar",
"Thousand Needles",
"Thunder Bluff",
"Un'Goro Crater",
"Winterspring",
};
VerisimilarGM.zoneList.outlands={
"Blade's Edge Mountains",
"Hellfire Peninsula",
"Nagrand",
"Netherstorm",
"Shadowmoon Valley",
"Shattrath City",
"Terokkar Forest",
"Zangarmarsh",
};
VerisimilarGM.zoneList.northrend={
"Borean Tundra",
"Crystalsong Forest",
"Dalaran",
"Dalaran Sewers",
"Dragonblight",
"Grizzly Hills",
"Howling Fjord",
"Hrothgar's Landing",
"Icecrown",
"Sholazar Basin",
"The Storm Peaks",
"Wintergrasp",
"Zul'Drak",
};
VerisimilarGM.zoneList.battlegrounds={
"Alterac Valley",
"Arathi Basin",
"Eye of the Storm",
"Isle of Conquest",
"Strand of the Ancients",
"Warsong Gulch",
};

VerisimilarGM.zoneList.dungeons={
"Auchindoun: Auchenai Crypts",
"Auchindoun: Mana-Tombs",
"Auchindoun: Sethekk Halls",
"Auchindoun: Shadow Labyrinth",
"Azjol-Nerub: Ahn'kahet: The Old Kingdom",
"Azjol-Nerub: Azjol-Nerub",
"Blackfathom Deeps",
"Blackrock Depths",
"Blackrock Spire",
"Caverns of Time: Old Hillsbrad Foothills",
"Caverns of Time: The Black Morass",
"Caverns of Time: The Culling of Stratholme",
"Coilfang Reservoir: The Slave Pens",
"Coilfang Reservoir: The Steamvault",
"Coilfang Reservoir: The Underbog",
"Crusaders' Coluseum: Trial of the Champion",
"Dire Maul",
"Drak'Tharon Keep",
"Gnomeregan",
"Gundrak",
"Hellfire Citadel: Hellfire Ramparts",
"Hellfire Citadel: The Blood Furnace",
"Hellfire Citadel: The Shattered Halls",
"Magisters' Terrace",
"Maraudon",
"Ragefire Chasm",
"Razorfen Downs",
"Razorfen Kraul",
"Scarlet Monastery",
"Scholomance",
"Shadowfang Keep",
"Stratholme",
"Sunken Temple",
"Tempest Keep: The Arcatraz",
"Tempest Keep: The Botanica",
"Tempest Keep: The Mechanar",
"The Deadmines",
"The Nexus: The Nexus",
"The Nexus: The Oculus",
"The Stockade",
"The Violet Hold",
"Uldaman",
"Ulduar: Halls of Lightning",
"Ulduar: Halls of Stone",
"Utgarde Keep: Utgarde Keep",
"Utgarde Keep: Utgarde Pinnacle",
"Wailing Caverns",
"Zul'Farrak",
};

VerisimilarGM.zoneList.raids={
"Black Temple",
"Blackwing Lair",
"Caverns of Time: Hyjal Summit",
"Coilfang Reservoir: Serpentshrine Cavern",
"Crusaders' Coluseum: Trial of the Crusader",
"Gruul's Lair",
"Hellfire Citadel: Magtheridon's Lair",
"Karazhan",
"Molten Core",
"Naxxramas",
"Onyxia's Lair",
"Ruins of Ahn'Qiraj",
"Sunwell Plateau",
"Tempest Keep: The Eye",
"Temple of Ahn'Qiraj",
"The Nexus: The Eye of Eternity",
"The Obsidian Sanctum",
"Ulduar",
"Vault of Archavon",
"Zul'Aman",
"Zul'Gurub",
};

VerisimilarGM.eventList={"Kill","Subzone","Script"};